print("decimal number 's 10 is", 10, ".")
print("binary number 's 10 is", 0b10, ".")
print("octal number 's 10 is", 0o10, ".")
print("Hexadecimal number 's 10 is", 0x10, ".")
print("Hexadecimal number 's F is", 0xF, ".")